### ISSUE TITLE
email/pass for demo?

### ISSUE THREAD

**Issue by ageorgios** [OskarD/TubeTracker#1]
Hello

Can you please provide demo credentials?

**Comment by OskarD** [comment]
Hello @ageorgios!

You should be able to register on the demo and make your own account. Please let me know if it doesn't work.

The application is currently lacking in features, just so you know, though. It is very basic right now, but I am hoping to be able to complement it soon with some more useful things.

**Comment by ageorgios** [comment]
ok thank you it works
i really like your idea and look forward to seeing it upgraded with more features, like history of stats and maybe graphs. Subscribers is also a very important stat to track!

Thank you for your work so far!
